name: Publish Any Commit

on:
  push:
    branches:
      - main
    tags:
      - '!**'
    paths:
      - 'src/**'
      - package.json
      - tsup.config.ts

jobs:
  build:
    if: "!startsWith(github.event.pull_request.title, 'renovate/')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install ni
        run: pnpm i -g @antfu/ni

      - name: Build
        run: nr build

      - name: Release
        run: pnpm dlx pkg-pr-new publish
